### ISSUE TITLE
@WithTimeout does not change/affect the global PageFactory timeout 

### ISSUE THREAD

**Issue by Ser-Gius** [appium/java-client#537]
## Description

I have a PageFactory class which is initiated like this:
```
homeScreen = new HomeScreen(driver);
PageFactory.initElements(new AppiumFieldDecorator(driver,
                        new TimeOutDuration(10, TimeUnit.SECONDS)),
                homeScreen);
```

Then inside the HomeScreen class I have a variety of elements. Now I want to change(reduce) the TimeOut duration for some of them so I use
```
@WithTimeout(time = 2500, unit = TimeUnit.MILLISECONDS)
//some locator
MobileElement element;
```

However this has no effect on the time the driver takes to search for the element, the duration is still 10 seconds.

## Environment

* java client build version or git revision if you use some shapshot: 4.1.1
* Appium server version or git revision if you use some shapshot: 1.6.1
* Desktop OS/version used to run Appium if necessary: MacOS 10.12
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 7.1.1
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real device

## Details

NA

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

NA

## Link to Appium logs

NA

**Comment by TikhomirovSergey** [comment]
@Ser-Gius This issue has been fixed. #467. The 5.0.0-beta is coming soon.

**Comment by sleknizi** [comment]
Hello @TikhomirovSergey ,
I still have the same issue on Appium java client : 6.1.0
@WithTimeout(time = 5, chronoUnit = ChronoUnit.SECONDS) does not change the global PageFactory timeout.
